apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 5ud03r5app
  namespace: argocd
  labels:
    app.kubernetes.io/name: 5ud03r5app
spec:
  project: default

  source:
    repoURL: https://github.com/freddyfchuquimiach-sketch/5ud03r5app.git
    targetRevision: main
    path: deploy/overlays/production
    # ¡¡ESTO ES LO QUE HACE QUE KUSTOMIZE FUNCIONE!!
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true