apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 5ud03r5app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/freddyfchuquimiach-sketch/5ud03r5app.git
    targetRevision: main
    path: deploy/overlays/production
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true